plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'top.niunaijun.webviewprobe'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId 'top.niunaijun.webviewprobe'
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
        performance {
            initWith release
            debuggable false
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            output.outputFileName = "WebViewProbe_${variant.versionName}_${output.baseName}.apk"
        }
    }
}

dependencies {
}
